### ISSUE TITLE
ip normalization doesn't work at Win10 

### ISSUE THREAD

**Issue by kimjw001** [chuckablack/python-52-weeks#3]
In win 10 ,

PS C:\Python37\Practices\quokka> & C:/Python37/python.exe c:/Python37/Practices/quokka/m01_basics/l_13.normalize_data.py

Normalization tests

--String lower() normalization works
--String casefold() normalization works
--MAC address normalization works
Traceback (most recent call last):
  File "c:/Python37/Practices/quokka/m01_basics/l_13.normalize_data.py", line 79, in <module>
    if IPv4Address(ip_addr_1) == IPv4Address(ip_addr_2) == IPv4Address(ip_addr_3):
  File "C:\Python37\lib\ipaddress.py", line 1327, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "C:\Python37\lib\ipaddress.py", line 1166, in _ip_int_from_string
    raise AddressValueError("%s in %r" % (exc, ip_str)) from None
ipaddress.AddressValueError: Ambiguous (octal/decimal) value in '010' not permitted in '010.00.01.001'
PS C:\Python37\Practices\quokka>

**Comment by kimjw001** [comment]
In Linux ,
It works .

**Comment by chuckablack** [comment]
Are the Python version you are running, Python 3.7.x? I notice the directory is C:\Python37\lib... . I mention this because the issue seems to be in the IPv2Address package, and perhaps that has been updated?

On my development system, which is Ubuntu, I'm using Python 3.8.5. Perhaps it will behave differently with a newer version of Python on your Windows 10 system?

It may not, I'm just speculating. It is complaining about the strange IP addresses I'm attempting to pass in - with leading zeros - so if still isn't working, you can safely delete or comment out that line with the leading zeros.

**Comment by chuckablack** [comment]
I ran this on my Windows 10 host, with Python 3.8 in PyCharm, and it runs fine. I also ran it in Windows 10 from the command line, where it is running Python 3.9.1, and it also runs fine. So I'm suspecting that the issue is with the version of Python you are running.

So my recommendation would be to update your Python version, and see if that resolves the problem.

**Comment by kimjw001** [comment]
Thanks for replying about my question.

Yes it works for me after deleting leading zeo.

Regards,


Jeff Kim

213-200-9134

**Comment by chuckablack** [comment]
Have you tried updating your Python version? On my Windows 10 system, the
code works fine with both 3.8.5 and 3.9.

**Comment by kimjw001** [comment]
Thanks Chuck ,

I have tried it with python 3.9.1 and it works fine.

Regards,


Jeff Kim

213-200-9134
